#%RAML 1.0 Library
usage: This library defines data types for auth operations

types:
  refresh-token-body: !include types/refresh-token-body-type.raml
  signin-credentials: !include types/signin-credentials-type.raml
  signup-credentials: !include types/signup-credentials-type.raml
  tokens-response: !include types/auth-response-type.raml
  change-password-body: !include types/change-password-body-type.raml