#%RAML 1.0 Library

traits:
  auth-headers: !include traits/auth-headers-trait.raml
  iss-header: !include traits/iss-header-trait.raml
  client-id-sec-headers: !include traits/client-id-secret-headers.raml