#%RAML 1.0 Library

types:
  email_address:
    type: !include types/email_address_type.raml
    example: !include examples/email_address_example.raml
  refresh_token_body:
    type: !include types/refresh_token_body_type.raml
    example: !include examples/refresh_token_body_example.raml
  signin_type:
    type: !include types/signin_credentials_type.raml
    example: !include examples/signin_credentials_example.raml
  signup_type:
    type: !include types/signup_credentials_type.raml
    example: !include examples/signup_credentials_example.raml
  succesfull_auth_response:
    type: !include types/succesfull_auth_response_type.raml
    example: !include examples/succesfull_auth_response_example.raml
