#%RAML 1.0 Trait

headers:
  Authorization:
    description: Authorization header with JWT token
    required: true
    type: string
    example: "Bearer ewogICJhbGciOiAiSFMyNTYiLAogICJ0eXAiOiAiSldUIiwKICAia2lkIjogIm11bGVfaXRzbm9vZ2VfY21zX3JzMjU2Igp9.ewogICJpc3MiOiAicG9zdG1hbi10ZXN0cyIsCiAgInN1YiI6ICJ0ZXN0XzFAbWFpbC5jb20iLAogICJ0b2tlbl90eXBlIjogImFjY2Vzc190b2tlbiIsCiAgImlhdCI6IDE3MDQ2NDkzNzgsCiAgImV4cCI6IDE3MDQ2NTI5NzgKfQ.ENpifTNUQFPOCZ32bPud04UcgfmYwNlOyJRzeEihrBo"