#%RAML 1.0 Trait

headers:
  client_id:
    description: Header required by Client ID Enforcement Policy
    required: true
    type: string
    example: "9zdG1hbi10ZXN0cyIsCiAgInN1YiI6ICJ0"
  client_secret:
    description: Header required by Client ID Enforcement Policy
    required: true
    type: string
    example: "9zdG1hbi10ZXN0cyIsCiAgInN1YiI6ICJ0"