#%RAML 1.0
title: user_auth_ddb-sys-api
description: API connected with AWS Dynamo DB to authorize users

version: v1
baseUri: /api/v1/auth/credentials
protocols:
  - HTTPS

uses: 
  credentials-library: exchange_modules/46a3d09d-1bf1-4bb2-8902-b31080f34dab/auth-credentials-types-examples/1.0.0/auth-credentials-types-examples.raml
  security-library: exchange_modules/46a3d09d-1bf1-4bb2-8902-b31080f34dab/security-library/1.0.3/security-library.raml

traits:
  errors: !include exchange_modules/46a3d09d-1bf1-4bb2-8902-b31080f34dab/error-response-trait/1.0.0/error-response-trait.raml

/signup:
  post:
    description: Create user credentials in database and return auth token
    is:
      - errors
      - security-library.iss-header
      - security-library.client-id-sec-headers
    body:
      application/json:
        type: credentials-library.signup_type
    responses:
      201:
        body:
          application/json:
            type: credentials-library.succesfull_auth_response

/signin:
  post:
    description: Authorize user by sent credentials
    is:
      - errors
      - security-library.iss-header
      - security-library.client-id-sec-headers
    body:
      application/json:
        type: credentials-library.signin_type
    responses:
      200:
        body:
          application/json:
            type: credentials-library.succesfull_auth_response

/signout:
  post:
    description: Remove refresh token from the database
    is:
      - errors
      - security-library.client-id-sec-headers
    body:
      application/json:
        type: credentials-library.email_address
    responses:
      204:

/refresh:
  post:
    description: Get new access token by sending refresh token
    is:
      - errors
      - security-library.iss-header
      - security-library.client-id-sec-headers
    body:
      application/json:
        type: credentials-library.refresh_token_body
    responses:
      201:
        body:
          application/json:
            type: credentials-library.succesfull_auth_response
